/* === GET_USER === */
export const GET_USER = 'GET_USER';
/* === ORDER === */
export const ADD_ORDER = 'ADD_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ALL_ORDER = 'DELETE_ALL_ORDER';

export const GET_CART_BY_USER = "GET_CART_BY_USER";
export const GET_ORDER_APPROVAL = 'GET_ORDER_APPROVAL';
export const UPDATE_ORDER_APPROVAL = 'UPDATE_ORDER_APPROVAL';
export const CANCEL_ORDER_APPROVAL = 'CANCEL_ORDER_APPROVAL';

export const CHANGE_PURCHASING_ORDER = 'CHANGE_PURCHASING_ORDER';
export const UPDATE_STATUS_PURCHASING_ORDER = 'UPDATE_STATUS_PURCHASING_ORDER';
export const STATUS_APPROVAL = 'STATUS_APPROVAL';
/* === ORDER === */
/* === PURCHASE === */
export const GET_PURCHASE_HEADER = 'GET_PURCHASE_HEADER';
export const GET_PURCHASE_LINE = 'GET_PURCHASE_LINE';
export const DELETE_PURCHASE_LINE = 'DELETE_PURCHASE_LINE';
export const ADD_PURCHASE_LINE = 'ADD_PURCHASE_LINE';
export const UPDATE_PURCHASE_HEADER = 'UPDATE_PURCHASE_HEADER';

/* === PURCHASE === */
